### PR TITLE
ui: Enable both native and webui on single binary

### LINKED ISSUE #344: ui: Enable Compilation with both web-ui and native-ui for easier binary distribution
Hi, I was in the process of fixing the packaging this for nixos, so that both the native-ui and the web-ui were working. However, when I was compiling it with both feature flags enabled I got this following error:

```
   Compiling clap v4.5.40
   Compiling yosemite v0.7.0
   Compiling emissary-util v0.4.0 (/build/source/emissary-util)
   Compiling emissary-cli v0.4.0 (/build/source/emissary-cli)
error[E0428]: the name `main` is defined multiple times
   --> emissary-cli/src/main.rs:472:1
    |
403 | fn main() -> anyhow::Result<()> {
    | ------------------------------- previous definition of the value `main` here
...
472 | fn main() -> anyhow::Result<()> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `main` redefined here
    |
    = note: `main` must be defined only once in the value namespace of this module

error: native and web ui cannot be enabled at the same time
  --> emissary-cli/src/main.rs:59:1
   |
59 | compile_error!("native and web ui cannot be enabled at the same time");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

We totally could just ship 2 binaries with the different features enabled, but I thought it would be good to see if it is part of the plan to keep the different UI's in the different binaries indefinitely. If not I threw together a quick branch that fixes this: https://github.com/cappuccinocosmico/emissary/tree/enable-both-native-and-webui-on-single-binary. If this isn't part of the project vision feel free to ignore :)

### PR DESCRIPTION
**Pull request by cappuccinocosmico**
Includes the fix mentioned in https://github.com/eepnet/emissary/issues/344.

### CODE REVIEW

File: emissary-cli/src/main.rs [hunk 1]
```diff
@@ -468,8 +467,68 @@ async fn native_main() -> anyhow::Result<()> {
...
+        match router_ui_config {
+            None => {
+                runtime.block_on(router_event_loop(router, port_mapper, shutdown_rx));
+            }
+            Some(RouterUiConfig { .. }) => {
+                tokio::spawn(async move {
+                    router_event_loop(router, port_mapper, shutdown_rx).await;
+                    std::process::exit(0);
+                });
+                ui::native::RouterUi::start(
```
Comment (altonen) [inline emissary-cli/src/main.rs:519]: After iced upgrade (https://github.com/eepnet/emissary/pull/320), the native UI internally calls `tokio::spawn()` so a runtime must be active. With these changes alone the native UI is unable to start but with the patch below both UIs work:

```patch
diff --git a/emissary-cli/src/main.rs b/emissary-cli/src/main.rs
index 7d1eeb3..c4ef0db 100644
--- a/emissary-cli/src/main.rs
+++ b/emissary-cli/src/main.rs
@@ -55,8 +55,6 @@ mod tools;
 mod tunnel;
 mod ui;
 
-
-
 /// Logging target for the file.
 const LOG_TARGET: &str = "emissary";
 
@@ -474,10 +472,10 @@ fn main() -> anyhow::Result<()> {
 }
 
 #[cfg(all(feature = "native-ui", feature = "web-ui"))]
-fn main() -> anyhow::Result<()> {
-    let runtime = tokio::runtime::Runtime::new()?;
+#[tokio::main]
+async fn main() -> anyhow::Result<()> {
     let (shutdown_tx, shutdown_rx) = channel(1);
-    let arguments = runtime.block_on(parse_arguments());
+    let arguments = parse_arguments().await;
     let RouterContext {
         router,
         port_mapper,
@@ -488,30 +486,30 @@ fn main() -> anyhow::Result<()> {
         address_book_handle,
         router_id,
         ..
-    } = runtime.block_on(setup_router::<TokioRuntime>(arguments))?;
+    } = setup_router::<TokioRuntime>(arguments).await?;
 
     let use_web_ui = router_ui_config.as_ref().and_then(|c| c.web_ui).unwrap_or(false);
 
     if use_web_ui {
         match router_ui_config {
             None => {
-                runtime.block_on(router_event_loop(router, port_mapper, shutdown_rx));
+                router_event_loop(router, port_mapper, shutdown_rx).await;
             }
             Some(RouterUiConfig {
                 refresh_interval,
                 port,
                 ..
             }) => {
-                runtime.spawn(async move {
+                tokio::spawn(async move {
                     ui::web::RouterUi::new(events, port, refresh_interval, shutdown_tx).run().await;
                 });
-                runtime.block_on(router_event_loop(router, port_mapper, shutdown_rx));
+                router_event_loop(router, port_mapper, shutdown_rx).await;
             }
         }
     } else {
         match router_ui_config {
             None => {
-                runtime.block_on(router_event_loop(router, port_mapper, shutdown_rx));
+                router_event_loop(router, port_mapper, shutdown_rx).await;
             }
             Some(RouterUiConfig { .. }) => {
                 tokio::spawn(async move {

```

**Review by altonen — APPROVED** [review]
